# Generated by Django 6.0.6 on 2026-06-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccueilConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre_site", models.CharField(blank=True, max_length=255, null=True)),
                ("sous_titre", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="accueil/hero/"),
                ),
                (
                    "titre_galeries",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "titre_acces_prive",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description_acces_prive", models.TextField(blank=True, null=True)),
                (
                    "modal_titre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("modal_sous_titre", models.TextField(blank=True, null=True)),
                (
                    "modal_placeholder_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuration de la page d'accueil",
            },
        ),
        migrations.CreateModel(
            name="SectionAccueil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "contenu",
                    models.TextField(help_text="Contenu de la section (HTML autorisé)"),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("hero", "Section Hero"),
                            ("galeries", "Avant les galeries"),
                            ("prive", "Avant accès privé"),
                            ("footer", "Avant le footer"),
                        ],
                        help_text="Position de la section sur la page",
                        max_length=20,
                    ),
                ),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0, help_text="Ordre d'affichage (plus petit en premier)"
                    ),
                ),
                (
                    "est_active",
                    models.BooleanField(
                        default=True, help_text="Afficher cette section"
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Section d'accueil",
                "verbose_name_plural": "Sections d'accueil",
                "ordering": ["position", "ordre", "titre"],
            },
        ),
    ]
