# Generated by Django 6.0.6 on 2026-06-17 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accueil", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accueilconfig",
            options={
                "verbose_name": "Configuration de la page d'accueil",
                "verbose_name_plural": "Configuration de la page d'accueil",
            },
        ),
    ]
