# Generated by Django 6.0.6 on 2026-06-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accueil", "0002_alter_accueilconfig_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="accueilconfig",
            name="btn_acces_prive",
            field=models.CharField(
                default="Accès privé", max_length=50, verbose_name="Bouton accès privé"
            ),
        ),
        migrations.AddField(
            model_name="accueilconfig",
            name="btn_voir_galeries",
            field=models.CharField(
                default="Voir les galeries",
                max_length=50,
                verbose_name="Bouton galeries",
            ),
        ),
        migrations.AddField(
            model_name="accueilconfig",
            name="hero_description",
            field=models.TextField(
                default="Capturer l'instant, révéler l'émotion.",
                verbose_name="Description hero",
            ),
        ),
        migrations.AddField(
            model_name="accueilconfig",
            name="hero_sous_titre",
            field=models.CharField(
                default="Studio photographique",
                max_length=100,
                verbose_name="Sous-titre hero",
            ),
        ),
        migrations.AddField(
            model_name="accueilconfig",
            name="modal_btn_acceder",
            field=models.CharField(
                default="Accéder à la galerie",
                max_length=50,
                verbose_name="Bouton accès galerie",
            ),
        ),
        migrations.AddField(
            model_name="accueilconfig",
            name="modal_btn_entrer_code",
            field=models.CharField(
                default="Entrer mon code", max_length=50, verbose_name="Bouton modal"
            ),
        ),
        migrations.AddField(
            model_name="accueilconfig",
            name="nom_site",
            field=models.CharField(
                default="Hors les Murs", max_length=100, verbose_name="Nom du site"
            ),
        ),
        migrations.AddField(
            model_name="accueilconfig",
            name="titre_complet",
            field=models.CharField(
                default="Hors les Murs — Studio Photographique",
                help_text="Titre affiché dans l'onglet du navigateur",
                max_length=200,
                verbose_name="Titre complet",
            ),
        ),
    ]
