# Generated by Django 6.0.6 on 2026-06-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accueil", "0003_accueilconfig_btn_acces_prive_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accueilconfig",
            options={
                "verbose_name": "Configuration",
                "verbose_name_plural": "Configurations",
            },
        ),
        migrations.AddField(
            model_name="accueilconfig",
            name="nav_acces_prive",
            field=models.CharField(
                default="Accès privé",
                max_length=50,
                verbose_name="Lien menu accès privé",
            ),
        ),
        migrations.AddField(
            model_name="accueilconfig",
            name="nav_galeries",
            field=models.CharField(
                default="Galeries", max_length=50, verbose_name="Lien menu galeries"
            ),
        ),
    ]
