# Generated by Django 6.0.6 on 2026-06-17 20:25

import django.db.models.deletion
import galeries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Galerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("est_publique", models.BooleanField(default=True)),
                (
                    "masonry_layout_manuel",
                    models.BooleanField(
                        default=True,
                        help_text="Ordre d'affichage défini par le photographe.",
                        verbose_name="Masonry manuel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Galerie",
                "verbose_name_plural": "Galeries",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True)),
                (
                    "masonry_layout_manuel",
                    models.BooleanField(
                        default=True,
                        help_text="Ordre d'affichage défini par le photographe.",
                        verbose_name="Masonry manuel",
                    ),
                ),
                (
                    "galerie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to="galeries.galerie",
                    ),
                ),
            ],
            options={
                "unique_together": {("galerie", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        storage=galeries.models.PhotoStorage(),
                        upload_to=galeries.models.photo_upload_path,
                    ),
                ),
                ("nom_fichier", models.CharField(editable=False, max_length=255)),
                ("taille", models.PositiveIntegerField(help_text="octets", null=True)),
                ("largeur", models.PositiveIntegerField(help_text="pixels", null=True)),
                ("hauteur", models.PositiveIntegerField(help_text="pixels", null=True)),
                ("titre", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("date_prise_de_vue", models.DateTimeField(blank=True, null=True)),
                ("appareil", models.CharField(blank=True, max_length=255)),
                ("objectif", models.CharField(blank=True, max_length=255)),
                (
                    "ouverture",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("vitesse", models.CharField(blank=True, max_length=20)),
                (
                    "iso",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ISO"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("auteur_nom", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "auteur_prenom",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "auteur_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                (
                    "collections",
                    models.ManyToManyField(
                        blank=True, related_name="photos", to="galeries.collection"
                    ),
                ),
                (
                    "galeries",
                    models.ManyToManyField(
                        blank=True, related_name="photos", to="galeries.galerie"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="photos", to="galeries.tag"
                    ),
                ),
            ],
        ),
    ]
