# Generated by Django 6.0.6 on 2026-06-17 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="ordre_affichage",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="galerie",
            name="ordre_affichage",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="AccesGalerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_acces",
                    models.CharField(
                        help_text="Code d'accès généré automatiquement",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "titre_acces",
                    models.CharField(
                        blank=True,
                        help_text="Titre personnalisé pour identifier cet accès (ex: 'Mariage Julie & Pierre')",
                        max_length=100,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "date_expiration",
                    models.DateTimeField(
                        blank=True,
                        help_text="Laissez vide pour un accès illimité",
                        null=True,
                    ),
                ),
                (
                    "nombre_max_visiteurs",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Nombre maximum de visiteurs autorisés (laissez vide pour illimité)",
                        null=True,
                    ),
                ),
                (
                    "permettre_telechargement",
                    models.BooleanField(
                        default=True,
                        help_text="Autoriser le téléchargement des photos haute résolution",
                    ),
                ),
                (
                    "nombre_acces",
                    models.PositiveIntegerField(
                        default=0, help_text="Nombre total d'accès avec ce code"
                    ),
                ),
                (
                    "est_actif",
                    models.BooleanField(
                        default=True, help_text="Désactiver temporairement cet accès"
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "galerie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acces_prives",
                        to="galeries.galerie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accès privé",
                "verbose_name_plural": "Accès privés",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="VisiteurGalerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(help_text="Email du visiteur", max_length=254),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True,
                        help_text="Nom du visiteur (optionnel)",
                        max_length=100,
                    ),
                ),
                (
                    "token_acces",
                    models.CharField(
                        help_text="Token unique pour l'authentification en session",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "date_premier_acces",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date du premier accès à la galerie",
                        null=True,
                    ),
                ),
                (
                    "date_dernier_acces",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date du dernier accès à la galerie",
                        null=True,
                    ),
                ),
                (
                    "nombre_visites",
                    models.PositiveIntegerField(
                        default=0, help_text="Nombre total de visites"
                    ),
                ),
                (
                    "est_actif",
                    models.BooleanField(
                        default=True,
                        help_text="Désactiver l'accès pour ce visiteur spécifique",
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "acces_galerie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visiteurs",
                        to="galeries.accesgalerie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visiteur",
                "verbose_name_plural": "Visiteurs",
                "ordering": ["-date_dernier_acces"],
                "unique_together": {("acces_galerie", "email")},
            },
        ),
    ]
