# Generated by Django 6.0.6 on 2026-06-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "galeries",
            "0002_collection_ordre_affichage_galerie_ordre_affichage_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="galerie",
            name="image_couverture",
            field=models.ImageField(blank=True, upload_to="galeries/couvertures/"),
        ),
        migrations.AddField(
            model_name="photo",
            name="est_couverture",
            field=models.BooleanField(
                default=False, verbose_name="Photo de couverture"
            ),
        ),
    ]
