# Generated by Django 6.0.6 on 2026-06-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeries", "0003_remove_photo_auteur_photo_auteur_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="iso",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ISO"
            ),
        ),
    ]
