# Generated by Django 6.0.6 on 2026-06-18 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("galeries", "0003_galerie_image_couverture_photo_est_couverture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="galerie",
            options={
                "ordering": ["ordre_affichage", "nom"],
                "verbose_name": "Galerie",
                "verbose_name_plural": "Galeries",
            },
        ),
    ]
