# Generated by Django 6.0.6 on 2026-06-18 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("galeries", "0004_alter_galerie_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["ordre_affichage", "nom"]},
        ),
    ]
