# Generated by Django 6.0.6 on 2026-06-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeries", "0005_alter_collection_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="ordre_photos",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="galerie",
            name="ordre_photos",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
