# Generated by Django 6.0.6 on 2026-06-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeries", "0006_alter_galerie_options_collection_galerie_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="nom",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
