# Generated by Django 6.0.6 on 2026-06-18 10:47

from django.db import migrations, models


def calculer_hash_photos_existantes(apps, schema_editor):
    from galeries.models import calculer_hash_fichier

    Photo = apps.get_model("galeries", "Photo")
    for photo in Photo.objects.exclude(image=""):
        try:
            with photo.image.open("rb") as fichier:
                photo.hash_fichier = calculer_hash_fichier(fichier)
        except (FileNotFoundError, ValueError):
            continue
        photo.save(update_fields=["hash_fichier"])


class Migration(migrations.Migration):

    dependencies = [
        ("galeries", "0006_collection_ordre_photos_galerie_ordre_photos"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="hash_fichier",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=64
            ),
        ),
        migrations.RunPython(
            calculer_hash_photos_existantes, migrations.RunPython.noop
        ),
    ]
