# Generated by Django 6.0.6 on 2026-06-18 22:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeries", "0007_photo_hash_fichier"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="date_chargement",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
